---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

image: debian:stable

pages:
  script:
    - mkdir public
    - cp ubuntu.csv debian.csv public/
  artifacts:
    paths:
      - public
  only:
    - main
